import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";

import { Providers } from "./providers";
import NavBar from "@/app/components/navBar";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar></NavBar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
